version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=wishwise
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 5

  frontend:
    container_name: frontend
    build:
      context: ./frontend/wishwise-front
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/wishwise-front/.env.production
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_NAME=wishwise
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - JWT_KEY=your-secret-key
    restart: always

volumes:
  db_data:
